### ISSUE TITLE
Cross origin requests denied for standalone markdown file

### ISSUE THREAD

**Issue by hsjunnesson** [BenTearzz/RemarkPortable#2]
I'm trying to include my presentation in a standalone markdown file `presentation.md`. Following the instructions I'm doing this: `<script>var slideshow = remark.create({sourceUrl: 'presentation.md'});</script>`

I'm opening `index.html` in Chrome and I get this error:

```
remark.min.js:17 Access to XMLHttpRequest at 'file:///.../presentation.md' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
c @ remark.min.js:17
remark.min.js:17 Uncaught Error
    at XMLHttpRequest.s.onerror (remark.min.js:17)
    at c (remark.min.js:17)
    at new r (remark.min.js:17)
    at r.create (remark.min.js:1)
    at index.html:11
```

**Comment by benstigsen** [comment]
Oh yeah I had forgotten all about that, thanks for reminding me! The error happens because it doesn't have access to the local filesystem, I do know how to fix this though! This can be fixed by adding a button that allows the user to choose a file.

I'll take a look at it later today, might only be fixed 1st or 2nd January. I'll let you know when I've fixed it.

**Comment by benstigsen** [comment]
I just want to let you know, I haven't forgotten about this, I've just been really busy with assignments!

**Comment by hsjunnesson** [comment]
Don't sweat it. I'm inlining the markdown in `index.html` for now.

**Comment by benstigsen** [comment]
Hi! Sorry about the delay, assignments have been keeping me busy, and still is.
But now two buttons have been added, one for loading the content itself and one for loading files. The buttons will be hidden when the browser / window enters fullscreen (F11).

There's a memory leak to fix, (it seems like a very minor one, but still one nonetheless).

I'd like to extend this to work with drag-and-drop as well. So that'll probably be added very soon.
